config/routes.rb
Rails.application.routes.draw do
  get 'home/index'
  get 'about' => 'pages#about'
  get 'services' => 'pages#services'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :barbers
  resource :appointments, only: [:new, :create], path_names: { :new => ''}
  resource :contacts, only: [:new, :create], path_names: { :new => '' }
  root 'home#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  validates :name, :phone, :barber, :datetime, presence: true
end

app/models/barber.rb
class Barber < ApplicationRecord
  has_one_attached :photo
  validates :name, :profession, :bio, presence: true
end

app/models/contact.rb
class Contact < ApplicationRecord
  validates :name, :email, :message, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

  def new
  end

  def create
    @appointment = Appointment.new(appointment_params)
    if @appointment.valid?
      @appointment.save
    else
      render action: 'new'
    end
  end

private
  
  def appointment_params
    params.require(:appointment).permit(:name, :phone, :barber, :datetime)
  end

end

app/controllers/barbers_controller.rb
class BarbersController < ApplicationController

  def index
    @barbers = Barber.all
  end

  def show
    @barber = Barber.find(params[:id])
  end

  def new
    @barber = Barber.new
  end

  def edit
    @barber = Barber.find(params[:id]) 
  end

  def create
    @barber = Barber.new(barber_params)

    if @barber.save
      redirect_to @barber
    else
      render 'new'
    end
  end

  def update
    @barber = Barber.find(params[:id])

    if @barber.update(barber_params)
      redirect_to @barber
    else
      render 'edit'
    end
  end

   def destroy
    @barber = Barber.find(params[:id])
    @barber.destroy

    redirect_to barbers_path
  end

private
  
  def barber_params
    params.require(:barber).permit(:photo, :name, :profession, :bio)
  end

end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController

  def new
  end

  def create
    @contact = Contact.new(contact_params)
    if @contact.valid?
      @contact.save
    else
      render action: 'new'
    end
  end

private
  
  def contact_params
    params.require(:contact).permit(:name, :email, :message)
  end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def about
  end

  def services
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/barbers_helper.rb
module BarbersHelper
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/appointments/create.html.erb
<section class="page-section cta">
      <div class="container">
      	<div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Wait for the call from us! It`s will be shortly</span>
              </h2>
            </div>
        </div>
    </div>
</div>
</section>

app/views/appointments/new.html.erb
  <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
<section class="page-section cta">
      <div class="container">
      	<%= form_for :appointment, url: appointments_path do |f| %>
			<% if @appointment && @appointment.errors.any? %>
				<p>
					<ul>
						<% @appointment.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>	
				</p>
			<% end %>
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Please, enlist!</span>
                <span class="section-heading-lower">Visit to us!</span>
              </h2>
            </div>
            <form name="sentMessage" id="contactForm" novalidate>
          		<div class="control-group">
            		<div class="form-group floating-label-form-group controls">
					<label>Name</label>
              			<%= f.text_field :name, class: "form-control", placeholder: "Name", id: "name" %>
              		<p class="help-block text-danger"></p>
            		</div>
          		</div>
          		<div class="control-group">
            		<div class="form-group floating-label-form-group controls">
					<label>Phone</label>
              			<%= f.text_field :phone, class: "form-control", placeholder: "Phone", id: "name" %>
              		<p class="help-block text-danger"></p>
            		</div>
          		</div>
		          <div class="control-group">
		              <%= f.select :barber, options_for_select(['Any barber', 'Lisa', 'Mona', 'Kate']) %>          
		          </div>
		           <div class="control-group">
            		<div class="form-group floating-label-form-group controls">
					<label>Datetime</label>
              			<%= f.text_field :datetime, class: "form-control", placeholder: "Date", id: "datepicker" %>
                      <script>
                        $( function() {
                          $( "#datepicker" ).datepicker();
                        } );
                      </script>
              		<p class="help-block text-danger">Choose your date. After that the barber will call you and negotiate about promptly time</p>
            		</div>
          		</div>
		          <br>
		          <div id="success"></div>
		          <div class="form-group">
		            <%= f.submit 'Enroll', class: "btn btn-primary", id: "sendMessageButton" %>
		          </div>
		       </form>
          </div>
        </div>
      </div>
    </section>	
<% end %>

app/views/barbers/_form.html.erb
<%= form_with model: @barber, local: true do |form| %>
 <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Create Barbie</span>
                <span class="section-heading-lower">Create new</span>
              </h2>
            </div>
            <form name="sentMessage" id="contactForm" novalidate>
          	<div class="control-group">
          		<div class="form-group floating-label-form-group controls">
          			<label>Photo</label>
					<%= form.file_field :photo %>
				</div>
            		<div class="form-group floating-label-form-group controls">
					<label>Name</label>
              			<%= form.text_field :name, class: "form-control", placeholder: "Name...", id: "name" %>
              		<p class="help-block text-danger"></p>
            		</div>
          		</div>
		          <div class="control-group">
		            <div class="form-group floating-label-form-group controls">
		              <label>Profession</label>
		              <%= form.text_field :profession, class: "form-control", placeholder: "Profession...", id: "name" %>
		              <p class="help-block text-danger"></p>
		            </div>
		          </div>
		          <div class="control-group">
		            <div class="form-group floating-label-form-group controls">
		              <label>Bio</label>
		              <%= form.text_area :bio, textarea_rows: "5", class: "form-control", placeholder: "Bio...", id: "message" %>
		              <p class="help-block text-danger"></p>
		            </div>
		          </div>
		          
		          <br>
		          <div id="success"></div>
		          <div class="form-group">
		            <%= form.submit 'Create Barber', class: "btn btn-primary", id: "sendMessageButton" %>
		          </div>
		       </form>
          </div>
        </div>
      </div>
    </section>	
<% end %>

app/views/barbers/edit.html.erb
<%= render 'form' %>

app/views/barbers/index.html.erb
<% @barbers.each do |barber| %>
<section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex ml-auto rounded">
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper"><%= barber.profession %></span>
              <span class="section-heading-lower"><%= barber.name %></span>
            </h2>
          </div>
        </div>
        <%= image_tag(barber.photo, class: "product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0") %>
        <div class="product-item-description d-flex mr-auto">
          <div class="bg-faded p-5 rounded">
            <p class="mb-0"><%= barber.bio %></p>
          </div>
        </div>
      </div>
    </div>
  </section>
<% end %>

app/views/barbers/new.html.erb
<%= render 'form' %>

app/views/barbers/show.html.erb
<section class="page-section">
    <div class="container">
      <div class="product-item">
        <div class="product-item-title d-flex">
          <div class="bg-faded p-5 d-flex ml-auto rounded">
            <h2 class="section-heading mb-0">
              <span class="section-heading-upper"><%= @barber.profession %></span>
              <span class="section-heading-lower"><%= @barber.name %></span>
            </h2>
          </div>
        </div>
        <%= image_tag(@barber.photo, class: "product-item-img mx-auto d-flex rounded img-fluid mb-3 mb-lg-0") %>
        <div class="product-item-description d-flex mr-auto">
          <div class="bg-faded p-5 rounded">
            <p class="mb-0"><%= @barber.bio %></p>
          </div>
    </div>
  </section>

app/views/contacts/create.html.erb
<section class="page-section cta">
      <div class="container">
      	<div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Wait for the response. It`s will be shortly</span>
                <span class="section-heading-lower">Thanks for the message!</span>
              </h2>
            </div>
        </div>
    </div>
</div>
</section>

app/views/contacts/new.html.erb
<section class="page-section cta">
      <div class="container">
      	<%= form_for :contact, url: contacts_path do |f| %>
			<% if @contact && @contact.errors.any? %>
				<p>
					<ul>
						<% @contact.errors.full_messages.each do |msg| %>
						<li><%= msg %></li>
						<% end %>
					</ul>	
				</p>
			<% end %>
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Come On</span>
                <span class="section-heading-lower">Contact Us</span>
              </h2>
            </div>
            <form name="sentMessage" id="contactForm" novalidate>
          		<div class="control-group">
            		<div class="form-group floating-label-form-group controls">
					<label>Name</label>
              			<%= f.text_field :name, class: "form-control", placeholder: "Name", id: "name" %>
              		<p class="help-block text-danger"></p>
            		</div>
          		</div>
		          <div class="control-group">
		            <div class="form-group floating-label-form-group controls">
		              <label>Email Address</label>
		              <%= f.text_field :email, class: "form-control", placeholder: "Email Address", id: "email" %>
		              <p class="help-block text-danger"></p>
		            </div>
		          </div>
		          <div class="control-group">
		            <div class="form-group floating-label-form-group controls">
		              <label>Message</label>
		              <%= f.text_area :message, textarea_rows: "5", class: "form-control", placeholder: "Message", id: "message" %>
		              <p class="help-block text-danger"></p>
		            </div>
		          </div>
		          <br>
		          <div id="success"></div>
		          <div class="form-group">
		            <%= f.submit 'Send Message', class: "btn btn-primary", id: "sendMessageButton" %>
		          </div>
		       </form>
          </div>
        </div>
      </div>
    </section>	
<% end %>

app/views/home/index.html.erb
  <section class="page-section clearfix">
    <div class="container">
      <div class="intro">
        <%= image_tag 'intro.jpg', class: "intro-img img-fluid mb-3 mb-lg-0 rounded" %>
        <div class="intro-text left-0 text-center bg-faded p-5 rounded">
          <h2 class="section-heading mb-4">
            <span class="section-heading-upper">Barbershop by Monti</span>
            <span class="section-heading-lower">Make yourself handsome!</span>
          </h2>
          <p class="mb-3">Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat!
          </p>
          <div class="intro-button mx-auto">
            <%= link_to "Appointment", appointments_path, class: "btn btn-primary btn-xl" %>
          </div>
        </div>
      </div>
    </div>
  </section>

  <section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">We Promise</span>
              <span class="section-heading-lower">To You</span>
            </h2>
            <p class="mb-0">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/layouts/_footer.html.erb
  <!-- Footer -->
  <footer class="footer text-faded text-center py-5">
    <div class="container">
      <p class="m-0 small">Copyright &copy; Your Website 2020</p>
    </div>
  </footer>

app/views/layouts/_header.html.erb
  <!-- Header -->
  <head>
	  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	  <meta name="description" content="">
	  <meta name="author" content="">
	  <!-- Custom fonts for this template -->
  		<link href="https://fonts.googleapis.com/css?family=Raleway:100,100i,200,200i,300,300i,400,400i,500,500i,600,600i,700,700i,800,800i,900,900i" rel="stylesheet">
  		<link href="https://fonts.googleapis.com/css?family=Lora:400,400i,700,700i" rel="stylesheet">
  </head>
  <header>
    <h1 class="site-heading text-center text-white d-none d-lg-block">
      <span class="site-heading-upper text-primary mb-3">Barbershop by Monti</span>
      <span class="site-heading-lower">Fashion Style</span>
    </h1>
  </header>

app/views/layouts/_navigation.html.erb
  <!-- Navigation -->
  <nav class="navbar navbar-expand-lg navbar-dark py-lg-4" id="mainNav">
    <div class="container">
      <a class="navbar-brand text-uppercase text-expanded font-weight-bold d-lg-none" href="#">Barbershop by Monti</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarResponsive">
        <ul class="navbar-nav mx-auto">
          <li class="nav-item px-lg-4">
            <%= link_to "Home", home_index_path, class: "nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "About", about_path, class: "nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Services", services_path, class: "nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Appointment", appointments_path, class: "nav-link text-uppercase text-expanded" %>
          </li>
          <li class="nav-item px-lg-4">
            <%= link_to "Contact", new_contacts_path, class: "nav-link text-uppercase text-expanded" %>
          </li>
            <li class="nav-item px-lg-4">
              <%= link_to "Barbers", barbers_path, class: "nav-link text-uppercase text-expanded" %>
            </li>
        </ul>
      </div>
    </div>
  </nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BarbershopByMonti</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
       <!-- Header -->
    <%= render 'layouts/header' %>
    <!-- Navigation -->
    <%= render 'layouts/navigation' %>
    <%= yield %>
        <!-- Footer -->
    <%= render 'layouts/footer' %>
  </body>
</html>

app/views/pages/about.html.erb
<section class="page-section cta">
    <div class="container">
      <div class="row">
        <div class="col-xl-9 mx-auto">
          <div class="cta-inner text-center rounded">
            <h2 class="section-heading mb-4">
              <span class="section-heading-upper">20 years together!</span>
              <span class="section-heading-lower">Join with us!</span>
            </h2>
            <p class="mb-0">Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua!</p>
          </div>
        </div>
      </div>
    </div>
  </section>

app/views/pages/services.html.erb
    <section class="page-section cta">
      <div class="container">
        <div class="row">
          <div class="col-xl-9 mx-auto">
            <div class="cta-inner text-center rounded">
              <h2 class="section-heading mb-5">
                <span class="section-heading-upper">Come On In</span>
                <span class="section-heading-lower">We're Open</span>
              </h2>
              <ul class="list-unstyled list-hours mb-5 text-left mx-auto">
                <li class="list-unstyled-item list-hours-item d-flex">
                  Sunday
                  <span class="ml-auto">Closed</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Monday
                  <span class="ml-auto">7:00 AM to 8:00 PM</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Tuesday
                  <span class="ml-auto">7:00 AM to 8:00 PM</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Wednesday
                  <span class="ml-auto">7:00 AM to 8:00 PM</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Thursday
                  <span class="ml-auto">7:00 AM to 8:00 PM</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Friday
                  <span class="ml-auto">7:00 AM to 8:00 PM</span>
                </li>
                <li class="list-unstyled-item list-hours-item d-flex">
                  Saturday
                  <span class="ml-auto">9:00 AM to 5:00 PM</span>
                </li>
              </ul>
              <p class="address mb-5">
                <em>
                  <strong>1116 Orchard Street</strong>
                  <br>
                  Golden Valley, Minnesota
                </em>
              </p>
              <p class="mb-0">
                <small>
                  <em>Call Anytime</em>
                </small>
                <br>
                (317) 585-8468
              </p>
            </div>
          </div>
        </div>
      </div>
    </section>

    <section class="page-section about-heading">
      <div class="container">
        <%= image_tag 'services.jpg', class: "img-fluid rounded about-heading-img mb-3 mb-lg-0" %>
        <div class="about-heading-content">
          <div class="row">
            <div class="col-xl-9 col-lg-10 mx-auto">
              <div class="bg-faded rounded p-5">
                <h2 class="section-heading mb-4">
                  <span class="section-heading-upper">Strong Hair, Strong Man</span>
                  <span class="section-heading-lower">About Us</span>
                </h2>
                <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
                <p class="mb-0">Duis aute irure dolor in reprehenderit in voluptate
                  <em>lust</em>
                  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
              </div>
            </div>
          </div>
        </div>
      </div>
    </section>